name: Create Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Bump version and create release
        id: create_release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          initial_version: 0.0.1
          
      - name: Build native binary
        run: python build_binaries.py --platform native
        
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
          
      - name: Build ARM64 binary
        run: python build_binaries.py --platform arm64
        
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_release.outputs.new_tag }}
          name: Release ${{ steps.create_release.outputs.new_tag }}
          body: ${{ steps.create_release.outputs.changelog }}
          files: |
            dist/milady*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}